### ISSUE TITLE
Black border on resizing

### ISSUE THREAD

**Issue by FloVanGH** [parasyte/pixels#106] opened 2020-07-20 05:38 UTC
When I resize the window on the minimal-winit example on macOS Catalina I've got a black border around the content. I have the same problem with the other examples.

![image](https://user-images.githubusercontent.com/6715107/87903318-fd604180-ca5b-11ea-85d6-06c1afaf01f1.png)

**Comment by JMS55** [comment] 2020-07-20 06:39
This is intended. Pixels will only scale the game when it can scale to a perfect integer, e.g. 2x, 3x, 4x, etc the initial size. Otherwise, the black borders are added.

**Comment by parasyte** [comment] 2020-07-20 07:02
I'm going to close this, since it is working as intended. However, I will accept feature requests for configuring how the scaling works. E.g. #89

**Closed by parasyte** 2020-07-20 07:02 UTC
Labels: wontfix
