### ISSUE TITLE
space invaders - panicked at attempt to subtract with overflow

### ISSUE THREAD

**Issue by rofrol** [parasyte/pixels#54] opened 2020-01-15 19:31 UTC
```bash
~/personal_projects/rust/vendor/parasyte/pixels (master)$ DEBUG=true RUST_BACKTRACE=1 cargo run --example invaders --features=invaders
    Finished dev [unoptimized + debuginfo] target(s) in 0.04s
     Running `target/debug/examples/invaders`
thread 'main' panicked at 'attempt to subtract with overflow', simple-invaders/src/debug.rs:40:25
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:61
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1028
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1412
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:65
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:50
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:188
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:205
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:464
  11: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:373
  12: rust_begin_unwind
             at src/libstd/panicking.rs:302
  13: core::panicking::panic_fmt
             at src/libcore/panicking.rs:139
  14: core::panicking::panic
             at src/libcore/panicking.rs:70
  15: simple_invaders::debug::draw_invaders
             at simple-invaders/src/debug.rs:40
  16: simple_invaders::World::draw
             at simple-invaders/src/lib.rs:317
  17: invaders::main::{{closure}}
             at examples/invaders/main.rs:43
  18: winit::platform_impl::platform::sticky_exit_callback
             at /home/roman/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.20.0-alpha4/src/platform_impl/linux/mod.rs:693
  19: winit::platform_impl::platform::x11::EventLoop<T>::run_return
             at /home/roman/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.20.0-alpha4/src/platform_impl/linux/x11/mod.rs:292
  20: winit::platform_impl::platform::x11::EventLoop<T>::run
             at /home/roman/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.20.0-alpha4/src/platform_impl/linux/x11/mod.rs:389
  21: winit::platform_impl::platform::EventLoop<T>::run
             at /home/roman/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.20.0-alpha4/src/platform_impl/linux/mod.rs:640
  22: winit::event_loop::EventLoop<T>::run
             at /home/roman/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.20.0-alpha4/src/event_loop.rs:148
  23: invaders::main
             at examples/invaders/main.rs:36
  24: std::rt::lang_start::{{closure}}
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/rt.rs:61
  25: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:48
  26: std::panicking::try::do_call
             at src/libstd/panicking.rs:287
  27: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:78
  28: std::panicking::try
             at src/libstd/panicking.rs:265
  29: std::panic::catch_unwind
             at src/libstd/panic.rs:396
  30: std::rt::lang_start_internal
             at src/libstd/rt.rs:47
  31: std::rt::lang_start
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/rt.rs:61
  32: main
  33: __libc_start_main
  34: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Game panicked couple of times, with or without `DEBUG=true`.

**Comment by rofrol** [comment] 2020-01-15 19:33
Looks like shotting at the edge of reactangle of invaders.

```bash
~/personal_projects/rust/vendor/parasyte/pixels (master)$ RUST_BACKTRACE=1 cargo run --example invaders --features=invaders
    Finished dev [unoptimized + debuginfo] target(s) in 0.04s
     Running `target/debug/examples/invaders`
thread 'main' panicked at 'attempt to subtract with overflow', /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libcore/ops/arith.rs:198:45
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:61
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1028
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1412
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:65
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:50
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:188
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:205
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:464
  11: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:373
  12: rust_begin_unwind
             at src/libstd/panicking.rs:302
  13: core::panicking::panic_fmt
             at src/libcore/panicking.rs:139
  14: core::panicking::panic
             at src/libcore/panicking.rs:70
  15: <usize as core::ops::arith::Sub>::sub
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libcore/ops/arith.rs:198
  16: <&usize as core::ops::arith::Sub<usize>>::sub
             at simple-invaders/src/lib.rs:1
  17: simple_invaders::collision::Collision::bullet_to_invader
             at simple-invaders/src/collision.rs:64
  18: simple_invaders::World::update
             at simple-invaders/src/lib.rs:235
  19: invaders::main::{{closure}}
             at examples/invaders/main.rs:117
  20: winit::platform_impl::platform::sticky_exit_callback
             at /home/roman/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.20.0-alpha4/src/platform_impl/linux/mod.rs:693
  21: winit::platform_impl::platform::x11::EventLoop<T>::run_return
             at /home/roman/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.20.0-alpha4/src/platform_impl/linux/x11/mod.rs:305
  22: winit::platform_impl::platform::x11::EventLoop<T>::run
             at /home/roman/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.20.0-alpha4/src/platform_impl/linux/x11/mod.rs:389
  23: winit::platform_impl::platform::EventLoop<T>::run
             at /home/roman/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.20.0-alpha4/src/platform_impl/linux/mod.rs:640
  24: winit::event_loop::EventLoop<T>::run
             at /home/roman/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.20.0-alpha4/src/event_loop.rs:148
  25: invaders::main
             at examples/invaders/main.rs:36
  26: std::rt::lang_start::{{closure}}
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/rt.rs:61
  27: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:48
  28: std::panicking::try::do_call
             at src/libstd/panicking.rs:287
  29: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:78
  30: std::panicking::try
             at src/libstd/panicking.rs:265
  31: std::panic::catch_unwind
             at src/libstd/panic.rs:396
  32: std::rt::lang_start_internal
             at src/libstd/rt.rs:47
  33: std::rt::lang_start
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/rt.rs:61
  34: main
  35: __libc_start_main
  36: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by parasyte** [comment] 2020-01-17 18:03
Hi, thanks, but this might be a duplicate of #11

**Comment by parasyte** [comment] 2020-01-20 20:04
I'm almost positive this is the same issue. Please respond here if this is a new bug and I'll reopen.

**Closed by parasyte** 2020-01-20 20:04 UTC
Labels: duplicate, question
