### ISSUE TITLE
Fix resize with wgpu 0.5

### ISSUE THREAD

**Issue by lovesegfault** [parasyte/pixels#68] opened 2020-04-13 06:54 UTC
I think I mangled something in #60 that caused window resizing to act weird.
![image](https://user-images.githubusercontent.com/7243783/79099362-795b3700-7d53-11ea-9617-eac4bd72f593.png)
Is this the correct behavior? Why doesn't the grid take up the whole screen? Perhaps that should be added to the example if not?

**Comment by parasyte** [comment] 2020-04-13 07:03
This looks correct to me. The pixel buffer won't take up the full window area because `pixels` is optimizing render quality by enforcing integer scaling only. (This would be a nice optional setting in `PixelsBuilder`.)

Relevant integer scaling code is here: https://github.com/parasyte/pixels/blob/37b90fe6b409cea8b52088bfea537e9d5e27c626/src/renderers.rs#L182-L186

The `floor()` is intentional.

**Comment by parasyte** [comment] 2020-04-18 22:21
@lovesegfault Does my last response make sense? Is there anything else to do here?

**Comment by parasyte** [comment] 2020-05-20 17:25
Going to close this, since the screenshot shows behavior is working as designed. Feel free to reopen if there is an issue I am unaware of.

**Closed by parasyte** 2020-05-20 17:25 UTC
Labels: question
